### ISSUE TITLE
How to keep scores in ouputted files?

### ISSUE THREAD

**Issue by eudesbarbosa** [WGLab/EHR-Phenolyzer#7]
Hi,

Is there a way to see the score in the output files? I'm interested in more than just the rank, the only way I found so far was to use the `--keeptmp` flag, is there another?

Thanks a lot.
Eudes

**Comment by kaichop** [comment]
-keeptmp should work and there is no other argument to do this.

**Comment by eudesbarbosa** [comment]
Thanks for the quick reply =)
